name: design
description: "A new Flutter project."

publish_to: 'none'
environment:
  sdk: '>=3.2.5 <4.0.0'
#  sdk: '>=3.3.0 <4.0.0'
#  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_ui_helper_dev: ^0.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  device_info_plus: ^9.1.2
  image_cropper: ^5.0.1
  permission_handler: ^11.3.0
  video_player: ^2.8.3
  path_drawing: ^1.0.1
  flutter_bloc: ^8.1.4
  dropdown_search: ^5.0.6
  dio: ^5.4.1
  get_it: ^7.6.7
  share_plus: ^7.2.2
  firebase_messaging: ^14.7.20
  fluttertoast: ^8.2.4
  file_picker: ^6.2.0
  equatable: ^2.0.5
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  flutter_local_notifications: ^17.0.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/splaasScreenImage/
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
